# Generated by Django 5.1.3 on 2024-12-03 17:43

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_blogindexpage_blogpage_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="tag",
        ),
        migrations.AddField(
            model_name="blogpage",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Text for a category above the title",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
