# Generated by Django 5.1.3 on 2024-11-19 14:04

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingListSignup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WaitingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        help_text="Text for a tag above the title",
                        max_length=255,
                    ),
                ),
                (
                    "waiting_title",
                    models.CharField(
                        blank=True,
                        help_text="Title for the waiting page",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description for the waiting page"
                    ),
                ),
                (
                    "show_signup",
                    models.BooleanField(
                        default=True, help_text="Show the signup form or not"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        help_text="Background color for the waiting page",
                        max_length=255,
                    ),
                ),
                (
                    "signup_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sign Up image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.DeleteModel(
            name="HomePage",
        ),
    ]
