# Generated by Django 5.1.3 on 2024-11-20 10:46

import django.db.models.deletion
from cuid2 import Cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_waitinglistsignup_waitingpage_delete_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitinglistsignup",
            name="referral_code",
            field=models.CharField(
                default=Cuid(length=10).generate, max_length=10
            ),
        ),
        migrations.AddField(
            model_name="waitinglistsignup",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The person who referred this user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="home.waitinglistsignup",
            ),
        ),
        migrations.AlterField(
            model_name="waitingpage",
            name="waiting_title",
            field=models.CharField(
                help_text="Title for the waiting page", max_length=255
            ),
        ),
    ]
