# Generated by Django 5.1.3 on 2024-12-04 14:00

import cuid2.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_waitinglistsignup_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='category',
            field=models.CharField(blank=True, choices=[('news', 'News'), ('press_release', 'Press Release'), ('blog', 'Blog'), ('article', 'Article'), ('case_study', 'Case Study'), ('white_paper', 'White Paper'), ('webinar', 'Webinar'), ('podcast', 'Podcast'), ('video', 'Video'), ('infographic', 'Infographic'), ('report', 'Report'), ('research', 'Research'), ('interview', 'Interview'), ('event', 'Event'), ('award', 'Award'), ('job_posting', 'Job Posting')], help_text='Text for a category above the title', max_length=255),
        ),
    ]
