# Generated by Django 5.1.5 on 2025-01-29 20:20

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_waitinglistsignup_referral_code_blogpagetag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waitinglistsignup",
            name="referral_code",
            field=models.CharField(
                default=utils.models.cuid2_generator,
                editable=False,
                max_length=10,
                unique=True,
            ),
        ),
    ]
