---
- name: Deploy Agora Application
  hosts: app
  become: yes
  vars:
    # app information
    app_name: agora
    app_user: agora
    app_group: www-data
    # where the app is on the internet
    app_domain: agora.gdn
    media_domain: agora-media.gdn
    # where the app is on the server
    app_dir: /opt/{{ app_name }}
    # where the app code is
    # todo(kisamoto): Create and encrypt the token
    github_token: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      623132663536313536
    repo_url: https://{{ github_token }}@github.com/agora-net/agora.net.git

  tasks:
    - name: Create app user
      user:
        name: "{{ app_user }}"
        shell: /bin/bash
        system: yes

    - name: Install system dependencies
      package:
        name:
          - git
          - python3
          - python3-pip
          - caddy
          - just
        state: present

    - name: Install pipenv
      pip:
        name: pipenv
        state: present

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: "0755"

    - name: Clone application repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
      become_user: "{{ app_user }}"

    - name: Install Python dependencies
      command:
        cmd: just install
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"

    - name: Run database migrations
      command:
        cmd: just migrate
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"

    - name: Build frontend assets
      command:
        cmd: just build-static
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"

    - name: Collect static files
      command:
        cmd: just collectstatic
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"

    - name: Install app systemd services
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      with_items:
        - src: templates/app.service.j2
          dest: /etc/systemd/system/{{ app_name }}.service
        - src: templates/app.socket.j2
          dest: /etc/systemd/system/{{ app_name }}.socket
      notify: restart app

    - name: Install Caddyfile
      template:
        src: templates/caddy/Caddyfile.j2
        dest: /etc/caddy/Caddyfile
        mode: "0644"
        validate: caddy validate --config %s
      notify: reload caddy

    - name: Enable and start services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - "{{ app_name }}"
        - caddy

  handlers:
    - name: restart app
      systemd:
        name: "{{ app_name }}"
        state: restarted
        daemon_reload: yes

    - name: reload caddy
      systemd:
        name: caddy
        state: reloaded
