# Generated by Django 5.1.5 on 2025-02-06 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_identityverification_verified_at_alter_agorauser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDateOfBirth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='day')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='month')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
