# Generated by Django 5.1.5 on 2025-02-07 10:53

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverification',
            name='identity_issuing_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
