# Generated by Django 5.1.5 on 2025-02-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_identityverification_identity_issuing_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='last_error_code',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='last_error_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
