# Generated by Django 5.2.3 on 2025-06-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_identityverification_last_error_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agorauser',
            name='visibility',
            field=models.CharField(choices=[('pub', 'Public'), ('hid', 'Hidden'), ('priv', 'Private')], default='hid', max_length=4, verbose_name='visibility'),
        ),
    ]
