# Generated by Django 5.1.5 on 2025-02-10 02:06

import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_userdateofbirth_day_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agorauser",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterModelOptions(
            name="identityverification",
            options={"ordering": ["-modified"]},
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=pictures.models.PictureField(
                aspect_ratios=["3/4"],
                blank=True,
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                null=True,
                pixel_densities=[1, 2],
                upload_to="profile_pics/",
            ),
        ),
    ]
