name: End-to-End Testing

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Install dependencies
        run: just install-python

      - name: Install playwright dependencies
        run: just install-playwright

      - name: Run end-to-end tests
        run: just e2e-test
